RDKVREFPLT-3098: Convert to use new override syntax
rdkcentral/meta-oss-vendor-raspberrypi pull request #17
Opened 2024-08-26 19:57 UTC by leenaS-d

2024-08-26 20:28 UTC, arun-madhavan-013 requested changes

2024-08-26 20:28 UTC, arun-madhavan-013 commented on recipes-graphics/westeros/westeros.bbappend
> +    sed -i -e 's/-lwesteros_simplebuffer:client/-lwesteros_compositor -lwesteros_simplebuffer:client/g' ${S}/rpi/westeros-sink/Makefile.am
Need to confirm the replacement is apt.

2024-08-26 20:30 UTC, leenaS-d commented on recipes-graphics/westeros/westeros.bbappend
> +    sed -i -e 's/-lwesteros_simplebuffer:client/-lwesteros_compositor -lwesteros_simplebuffer:client/g' ${S}/rpi/westeros-sink/Makefile.am
done

2024-08-26 20:34 UTC, arun-madhavan-013 approved these changes

2024-08-28 20:26 UTC, arun-madhavan-013 approved these changes

2024-08-28 20:26 UTC, merged